from openai import OpenAI
from dotenv import load_dotenv




load_dotenv()
client = OpenAI()


GPT_MODEL = "gpt-3.5-turbo"
GPT_TEMP = 0.3


def identify_words(text):
    language = "English"
    messages = [
        {"role": "system", "content": f"""You are an expert at identifying words in text. You will be provided with a string of text 
            generated by EasyOCR. The text will be read off of the spine of books. Some of the text will be gibberish, but some text 
            might contain information about books. Your goal is not to identify these books, but rather to identify all the {language}
            words in the text. There will be misspellings and spacing errors, so you will need to be creative in identifying words. 

            You must respond with a comma-separated list with all the words you can identify in the text. If you come across a group
            of words that is an identifiable name, phrase, title, etc, please group those words together and add them to the list as
            a single item. These words may not be next to one another in the text, so you will need to be use your knowledge of real 
            books and real words to identify them. 
            
            Discard any text that is not an {language} word/phrase, a name, a title, a date, or a publisher name. Anything else should 
            not be included in your response.

            Use your knowledge of the books that exist in the world to help you correctly identify words and phrases. 
            If you recognize an author's name, book title, or any other information that is related to a book, please correct 
            any spelling errors and add them to the list. 

            Here is the text for you to analyze: """ + text
        }
    ]

    response = client.chat.completions.create(
        model=GPT_MODEL,
        messages=messages,
        temperature=GPT_TEMP,
        max_tokens=1000,
    )

    return response.choices[0].message.content



def identify_book_info(text):
    # Use OpenAI to identify the book information.
    language = "English"
    messages = [
        {"role": "system", "content": f"""You have extensive knowledge about books and their details. Your task is to identify the 
         titles, authors, and any additional information from a list of comma-separated words extracted from book spines.
         You must identify the title and author of each book, as well as any other relevant information like publisher, publication 
         date, and ISBN. The order of information may vary, and there may be spelling errors in the text.
         
         Use your knowledge of real books to identify them accurately. Be cautious and provide real data; do not make up any book 
         titles or authors. Format your response as a JSON object with a list of books, each with properties -- title, author, 
         publisher, publication date, and ISBN.
         
         Properties other than title and author should be included only if you can deduce them from the text. 
         
         After analyzing the text once, repeat the task to ensure no books are missed. Here is the text for analysis, delimited by 
         three backticks: 
            
            ```{text}```

            """
        }
    ]

    response = client.chat.completions.create(
        model=GPT_MODEL,
        messages=messages,
        temperature=GPT_TEMP,
        max_tokens=1000,
    )

    return response.choices[0].message.content