# Generated by Django 5.0.4 on 2024-05-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="uploaded_image",
            field=models.ImageField(upload_to="uploaded_images"),
        ),
    ]
