# Generated by Django 5.0.4 on 2024-05-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_scan_uploaded_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="bbox_image",
            field=models.ImageField(blank=True, default="", null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="scan",
            name="scan_status",
            field=models.CharField(default="running", max_length=200),
        ),
        migrations.AddField(
            model_name="scan",
            name="text_images",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
