# Generated by Django 5.0.4 on 2024-05-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_scan_bbox_image_scan_scan_status_scan_text_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="scan_status",
            field=models.CharField(default="uninitialized", max_length=200),
        ),
    ]
